FROM python:3.8

# install protoc
ENV PROTOC_ZIP=protoc-3.15.6-linux-x86_64.zip
RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.15.6/$PROTOC_ZIP | bash \
    && unzip -o $PROTOC_ZIP -d /usr/local bin/protoc \
    && unzip -o $PROTOC_ZIP -d /usr/local 'include/*' \
    && rm -f $PROTOC_ZIP
ENV PATH="/usr/local/bin/protoc:${PATH}"

WORKDIR /graphhopper
COPY . .
